version: '3.9'
services:
  web:
    build: ./build/php
    depends_on:
      - db
    volumes:
      # - ./apps:/var/www/html/ # Apps stored in the same directory
      - ~/web:/var/www/html/ # Apps stored in a different directory
    ports:
      - 8000:80
  db:
    build: ./build/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100000000
    ports:
      - "8080:80"
volumes:
  apps:
  dbData: